# Dcokerfile - Docker build script for pollex-angular
#
#    Copyright (c) 2019 - Open Source Competencer Center ICMC-USP
#
#    This file is part of Pollex.
#
#    Pollex is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    Pollex is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.

# Application is currently based on Ubuntu and Python

FROM ubuntu:19.10
FROM python:3.7
FROM node:12.13.1

# Application home directory

WORKDIR /home/pollex

# Copy application files into the image

COPY pollex-angular/ ./pollex-angular
COPY frontend/ ./frontend

WORKDIR pollex-angular

# Seteup angular

RUN npm install
RUN npm install -g @angular/cli
RUN npm install -g jquery@1.9.1 --save

# By default, the container will listen to port 4200 internally

EXPOSE 4200

# Start

ENTRYPOINT [ "ng", "serve"]

